import './globals.scss'
import './common.css'
import './reset.css'
import './font.css'
import { Inter } from 'next/font/google'
import Header from './components/header.js'
import Footer from './components/footer.js'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='wrap'>
          <Header/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  )
}
